package observer;

public enum NotificationType {
    //ovde ce biti sve vrste poziva
    INFO, CANNOT_ADD_CHILD_TO_LEAF, CANNOT_REMOVE_ROOT,NAME_EMPTY, ADDED_CHILD, REMOVED_CHILD,
    SHOW_TAB, RENAME,CHANGE_PARENT, REMOVED,CHANGE_PARENT_VIEW,REMOVED_CHILD_PACKAGE,CHANGE_DIAGRAM_NAME,PROJECT_NOT_SELECTED,
    CHANGE_AUTHOR_NAME, CHANGE_PROJECT_NAME, DELETE_PARENT_PROJECT, CHILD_CHANGED, DIAGRAM_NOT_SELECTED;
}
